name: Deploy to GitHub Pages

on:
  # 1. Se ejecuta cada vez que subes cambios a la rama principal (main)
  push:
    branches: ["main"]

  # 2. Se ejecuta automáticamente cada 6 horas para buscar nuevos proyectos en tu cuenta de GitHub
  schedule:
    - cron: "0 */6 * * *"

  # 3. Te permite ejecutarlo manualmente con un botón desde la pestaña "Actions" en GitHub
  workflow_dispatch:

# Permisos necesarios para que el Action publique en GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24.15"
          cache: "npm"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: npm ci

      - name: Build static site (SSG)
        run: npx nuxi generate
        env:
          # Inyectamos tu usuario para que Nuxt haga las consultas a tu perfil en la build
          GITHUB_USERNAME: hf1nacl

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ".output/public"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
